# permissions for end users to edit mckubes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mc-kube
    app.kubernetes.io/managed-by: kustomize
  name: mckube-editor-role
rules:
- apiGroups:
  - mcoperator.sdv.com
  resources:
  - mckubes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mcoperator.sdv.com
  resources:
  - mckubes/status
  verbs:
  - get
